# -*- coding: utf-8 -*-
"""Lei de Planck Loop Aquecimento

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1efuIlsLj5g25K0mB3_WXTI7GFnwOr1nM
"""

import math
from scipy.integrate import quad
import serial
import time

h = 6.626e-34  # Constante de Planck
k = 1.381e-23  # Constante de Boltzmann
c = 299792458  # Velocidade da luz
o = 5.6703744e-8  # Constante de Stefan-Boltzmann

y = 2*math.pi*(k**4)/((h**3)*(c**2)) #Constante extraída da integral da Lei de Planck

def x(v, T):
    return (v * 1e12) * h / (k * T)

def planck(x):
    return (x**3) / ((math.e**x) - 1)

def integral(v1, v2, T):
    a = x(v1, T)
    b = x(v2, T)
    integral, error = quad(planck, a, b)
    return integral * y * (T**4)

def stef_boltz(T):
    return o * (T**4)

def rgb(T):
    integral_r = integral(384, 480, T)
    integral_o = integral(480, 510, T)
    integral_y = integral(510, 530, T)
    integral_g = integral(530, 610, T)
    integral_c = integral(610, 618, T)
    integral_b = integral(618, 665, T)
    integral_v = integral(665, 789, T)

    stef_boltz_T = stef_boltz(T)

    r = (integral_r + integral_o * 0.5 + integral_y + integral_v * 0.255) / stef_boltz_T
    g = (integral_g + integral_o * 0.5 + integral_y + integral_c) / stef_boltz_T
    b = (integral_b + integral_c + integral_v) / stef_boltz_T

    r = round(r * 255)
    g = round(g * 255)
    b = round(b * 255)

    return [r, g, b]

ser = serial.Serial('COMX',9600,timeout=1)

def enviar_csv(r, g, b):
    ser.write(f"{r},{g},{b}\n".encode())

try:
    temperatura = 500
    a = temperatura
    while True:
            while temperatura < 20000:
                cor_rgb = rgb(temperatura)
                enviar_csv(cor_rgb[0],cor_rgb[1],cor_rgb[2])
                temperatura += 5
            temperatura = a
            enviar_csv(0,0,0)
except (KeyboardInterrupt):
    enviar_csv(0,0,0)
    ser.close()
    print("Finalização da conexão")
except:
    print("Deu erro")
    ser.close()
else:
    enviar_csv(0,0,0)
    ser.close()